present:
	vhs cassette.tape
	img2pdf output/*.png -o output/presentation.pdf
	cp output/presentation.pdf ../content/presentation.pdf
altpresent:
	vhs cassette2.tape
	img2pdf output/*.png -o output/presentation_3x4.pdf

clean:
	rm ../content/presentation.pdf
	rm output/*
